### ISSUE TITLE
ULID from GUID does not always parse

### ISSUE THREAD

**Issue by jeffijoe** [RobThree/NUlid#21]
I ran into this issue while trying to convert a GUID to a ULID, but it happened randomly.

The following code should trigger it

```csharp
for (var i = 0; i < 100_000; i++)
{
    Ulid.Parse(new Ulid(Guid.NewGuid()).ToString());
}
```

The stack trace:

```
System.ArgumentOutOfRangeException : Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks. (Parameter 'ticks')
   at System.DateTime.ThrowTicksOutOfRange()
   at System.DateTimeOffset..ctor(Int64 ticks, TimeSpan offset)
   at NUlid.Ulid.FromUnixTimeMilliseconds(Int64 milliseconds)
   at NUlid.Ulid.ByteArrayToDateTimeOffset(Byte[] value)
   at NUlid.Ulid.Parse(ReadOnlySpan`1 span)
```

**Comment by RobThree** [comment]
That is because some (G|U)UIDs result in the `Time` part of the ULID having  value beyond [`DateTimeOffset.MaxValue`](https://msdn.microsoft.com/en-us/library/system.datetimeoffset.maxvalue.aspx). This is documented [here](https://github.com/RobThree/NUlid#components).

In all honesty I built this when the ULID spec was maybe weeks (first commit was june 2016, my first commit was aug. 2016 which was based on the code of [july 2016](https://github.com/ulid/javascript/tree/ae3d1f04d4368846f96e897deaa0d1430ecd1500) IIRC), old. I had little to no reference implementations and I have no idea what other implementations do. But I'm afraid all fixes I can come up with are breaking changes. That would mean we would need to start work on a 2.0 version. I am curious how 'the competition' ([Ulid](https://github.com/Cysharp/Ulid), [ulid.net](https://github.com/fvilers/ulid.net), [CSharp.Ulid](https://github.com/mcb2001/CSharp.Ulid), [FSharp.Ulid](https://github.com/lucasschejtman/FSharp.Ulid)) handle this - if at all. Also, [the spec](https://github.com/ulid/spec) never mentions conversion from/to (G|U)UIDs so I think you could consider the conversion from/to a (G|U)UID more of an unofficial 'extension' of the spec.

The `Parse` method isn't really intended to parse arbitrary (G|U)UIDs but rather (G|U)UIDs that were created *from* a ULID with the `ToGuid()` method. But the spec *does* mention "[128-bit compatibility with UUID](https://github.com/ulid/spec#universally-unique-lexicographically-sortable-identifier)". It's just that .Net doesn't handle dates beyond `9999-12-31`.

**Comment by jeffijoe** [comment]
That's fair! Thank you for the response and for the library! 🙌 

I had tried various tricks myself but was unable to mess with the first 8 bytes in a way to make them "wrap around", but to be fair I didn't spend an awful lot of time on it. The use case was to be able to generate a deterministic ULID. I decided to go back to UUIDs instead to prevent this from being an issue.

**Comment by RobThree** [comment]
>  The use case was to be able to generate a deterministic ULID.

From (G|U)UIDs? Those are usually (semi) random; so the ULID will be too.

Why don't you use `Ulid.NewUlid()` instead of `Guid.NewGuid()`?

**Comment by jeffijoe** [comment]
From a UUID v5 which is deterministic.

**Comment by RobThree** [comment]
> From a UUID v5 which is deterministic.

Hence the "usually" 😜 But, sure, they may be deterministic, however 'sortability-wise' they might as well be random; they aren't "linear" as far as I know.

Conclusion being: If you need to rely on UUID's then (this) ULID might not be the answer unless some bit-fiddling is done maybe to keep things in spec. You could consider subtracting UNIX epoch (1970-01-01) for example which should bring the time part into range (at the cost of interoperability with other ULID implementations). That could be easily implemented with an extension method. If you're interested I might give it a shot later today.

**Comment by jeffijoe** [comment]
I appreciate it! But I already yanked out ULIDs and replaced them with GUIDs in my entire codebase yesterday since I didn't want to end up with any surprises. 😄

**Comment by RobThree** [comment]
Too bad. But I understand 😆 

I might give an extension method a try nonetheless; may come in handy for other people running into this 'issue'.
