### ISSUE TITLE
NuGet Package with Source Files

### ISSUE THREAD

**Issue by rcollina** [RobThree/NUlid#5]
Hello,
First and foremost, thanks for NUlid! 
I'd love to use NUlid in one of our "core" libraries.

Not sure if you're familiar with [TinyIoC](https://github.com/grumpydev/TinyIoC); it has a "simple inclusion model". You basically get its source files, no assemblies to reference.

Would it be possible to have a "source only" package for NUlid?

Thank you, and apologies in advance if opening an "issue" is not the correct way to open requests.

Rob

**Comment by RobThree** [comment]
> Would it be possible to have a "source only" package for NUlid?

I'm not sure I understand the question? The source is available in this repository; would you want a single-file source? Or a NuGet packages with no binaries and just the source? Or...?

You could very well stuff all source into a single file, but that would mean having to sacrifice code readability and common conventions of each class/interface in it's own file. I could create a single file manually in the repository but that would mean double the maintenance when things change. Another option would be to include a build-step or something that 'auto generates' such a file but I'm not very keen on that idea (mostly because I wouldn't know how to go about implementing it (correcty)).

I also wonder what the use-case of this would be and what the benefits would be (if any) and if they would outweigh the cons...

---

Besides all that I would also like to point put [IdGen](https://github.com/RobThree/IdGen); I have no idea what your usecase is but you may want to consider IdGen too since it has similarities with this project but is a bit more flexible.

**Comment by rcollina** [comment]
Thanks for your reply.

Third option: NuGet package with no binaries, source files only.

When you add the TinyIoC package you get a .cs file in your project (as opposed to a reference to an assembly dropped in the /packages/ folder). Now, TinyIoC is one big file - I wouldn't mind getting an organized "NUlid" folder.

I concur it's not pretty, and from your standpoint is more work for no significant benefit. I'd say it helps in borderline scenarios where external assembly dependencies are "frowned upon".

Since I'm barely managing to introduce some internal NuGet packages, I wanted to cut down on "external dependencies", but NUlid looks pretty great for what we're doing, thus this request.

I could copy the files myself, and it's most likely what I'll end up doing, but I wouldn't get "update notifications".

Anyway, I thought I'd throw this out there - thank you for your feedback!

u: I'll check out IdGen too as well, thank you!

**Comment by RobThree** [comment]
I'll have to look into how to create a source-only nuget package but I'm open to creating/providing a `Nulid.Source` package or something. I am currently very busy so a PR with a `.nuspec` file or something would help speed things along.

**Comment by rcollina** [comment]
I'll see if I can help, I'm going to research a bit as well! Thanks for your time.

**Comment by rcollina** [comment]
My first fork! 😄 

I did manage to create an additional, source-only [nuspec](https://github.com/rcollina/NUlid/blob/master/Nulid.Sources.nuspec) file. Problem is, I can't build the documentation, and without documentation, nuget fails. I'm going to try without including the .chm file.

I also need to test actually referencing the package, so I need to setup a local nuget repo.

**Comment by RobThree** [comment]
> Problem is, I can't build the documentation, 

If you install [SHFB](https://github.com/EWSoftware/SHFB/releases/tag/v2017.1.28.0) you can 😉

> I also need to test actually referencing the package, so I need to setup a local nuget repo.

You can do that; another (maybe easier) option would be to just add a package source as a local directory:

![image](https://cloud.githubusercontent.com/assets/607888/22691950/0a71e1ee-ed3d-11e6-8ddc-cb80f02c500f.png)

Drop the `.nupkg` file in there and you should be good to go / test.

**Comment by rcollina** [comment]
Managed to install SHFB and build the CHM file. 
Added a local nuget repo.
Proceeded to package: `nuget pack Nulid.Sources.nuspec /outputdirectory c:/nuget/local`

![image](https://cloud.githubusercontent.com/assets/699839/22694629/3f601960-ed48-11e6-8b5f-efd62b189e7f.png)

(added my name just for fun)

![image](https://cloud.githubusercontent.com/assets/699839/22694429/81b79942-ed47-11e6-9ea9-2b5d8a633eb5.png)

Looks good to me! 😄

**Comment by RobThree** [comment]
Well, create a PR and I'll get this show on the road 😛

**Comment by rcollina** [comment]
📦 Right, I just need to learn how :p

**Comment by RobThree** [comment]
[Couldn't be more simple](https://help.github.com/articles/creating-a-pull-request/#creating-the-pull-request) 😉 

Oh, I'd appreciate the

`<projectUrl>https://github.com/rcollina/NUlid</projectUrl>`

to be

`<projectUrl>https://github.com/RobThree/NUlid</projectUrl>` 

in the `.nuspec` file since that is the 'canonical' version.

**Comment by RobThree** [comment]
I see [you removed your name](https://github.com/rcollina/NUlid/commit/79e889494485a9873092b4cc368b69618b07d172); you can leave that in! Credit where credit is due and all that 😉

**Comment by rcollina** [comment]
Sorry about the project url in the nuspec, I was messing around!

**Comment by RobThree** [comment]
No problem!

PR is merged. Some [finishing touches](https://github.com/RobThree/NUlid/commit/f0593fecc11d0b176494128f5f307ab033a10dd3) and then I'll publish the sources package on NuGet.org. Gimme a few minutes 😉 

Thanks for your work / efforts!

**Comment by rcollina** [comment]
Thank your for your time (and patience)!

**Comment by RobThree** [comment]
[I've published the package](https://www.nuget.org/packages/NUlid.Sources/) on nuget.org:

`[The] package has not been indexed yet. It will appear in search results and will be available for install/restore after indexing is completed.`

Normally this doesn't take more than 10 minutes tops (and you can always 'force' a download via the PM console: `PM> Install-Package NUlid.Sources`); however I can't find it (yet) nor download it. I'll give it some time.

---
Upd: it seems to have been indexed and is found now! Yay! 🎉
